### ISSUE TITLE
Documentation for Store Plugin

### ISSUE THREAD

**Issue by sanjeevdwivedi** [Microsoft/unityplugins#3]
- Need a document describing the flow of the APIs e.g. LoadLicenseXML is first API for testing simulator .. how to test it, how to use it.. and links to MSDN articles/APIs

**Comment by stammen** [comment]
MSDN Monetize your app
https://msdn.microsoft.com/en-us/library/windows/apps/mt219687.aspx

**Comment by sanjeevdwivedi** [comment]
Finished.
