### ISSUE TITLE
Please I need a video tutorial of how to set-up and configure

### ISSUE THREAD

**Issue by moodele** [microsoft/unityplugins#31]
Please I need a walkthrough of how to setup this plugins, I keep getting errors when I open the sample unity scene in quotes "The type or namespace 'UnityPlugins' does not exist in the namespace 'Microsoft'. Are you missing an assembly reference?".

**Comment by nguyenthanhliemfc** [comment]
Yes, vote for this!
I don't know where to start

**Comment by xnguyenvyx** [comment]
vote for this!
